---

- hosts: crayfish
  become: yes
  vars:
    php_enablerepo: "remi-php70"
    php_packages_state: "latest"

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.git
    - geerlingguy.composer
    - Islandora-Devops.crayfish

