---

- hosts: webserver
  become: yes

  # add some vars here so we can run with --start-at-task if desired
  vars:
    webserver_app_user: "{% if ansible_os_family == 'RedHat' %}apache{% else %}www-data{% endif %}"
    vagrant_user: "{% if ansible_os_family == 'RedHat' %}vagrant{% else %}ubuntu{% endif %}"

  tasks:
        
    - name: Add FITS requirement
      composer:
        command: config
        arguments: repositories.islandora_fits github https://github.com/roblib/islandora_fits.git
        working_dir: "{{ drupal_core_path }}/.."

    - name: Download islandora FITS module
      composer:
        command: require
        arguments: drupal/islandora_fits
        working_dir: "{{ drupal_core_path }}/.."
      become_user: vagrant

    - name: Install Islandora FITS module
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_fits"

    - name: Install FITS Microservice from Github
      git:
        repo: https://github.com/roblib/CrayFits.git
        dest: /var/www/html/CrayFits

    - name: Adding port 8050 for Fits
      lineinfile:
        path: "/etc/apache2/ports.conf"
        line: "Listen 8050"
        insertafter: "Listen 8000"
        
    - name: Restart apache
      service:
        name: apache2
        state: restarted
      become: true

    - name: Run Composer On Fits Microservice
      composer:
        command: install
        working_dir: /var/www/html/CrayFits
        
