- name: Adding extra packages for the RDM system
  hosts: webserver
  become: yes

  vars:
    rdm_drupal_composer_dependencies:
      - "dompdf/dompdf:*"
      - "drupal/conditional_fields:*" 
      - "drupal/markup:*"
      - "drupal/select_or_other:*"
      - "drupal/dynamic_entity_reference:2.0-alpha9" 
      - "drupal/clamav:*"
      - "drupal/entity_print:*"
      - "drupal/simple_sitemap:*"
      - "islandora-rdm/islandora_rdm:dev-8.x-1.x"
      - "islandora-rdm/islandora_rdm_multifile_media:dev-8.x-1.x"
      - "drupal/orcid:1.x-dev"
      - "islandora-rdm/tus:dev-8.x-1.x"
      - "drupal/uppy:1.x-dev"
      - "islandora-rdm/csv_field_preview"

    rdm_drupal_enable_modules:
      - conditional_fields
      - markup
      - select_or_other
      - clamav
      - entity_print
      - simple_sitemap
      - islandora_rdm
      - islandora_rdm_defaults
      - islandora_rdm_multifile_media
      - islandora_rdm_site
      - islandora_rdm_data_management_plan 
      - islandora_rdm_workflows
      - orcid
      - tus
      - uppy
      - csv_field_preview

  tasks:
    - name: Ubuntu packages for RDM
      package:
        name: "{{ item }}"
        state: present
      with_items: 
        - php7.2-zip
      when: ansible_os_family == "Debian"

    - name: Install RDM dependencies with composer require (this may take a while).
      composer:
        command: require
        arguments: "{{ item }}"
        working_dir: "{{ drupal_composer_install_dir }}"
      with_items: "{{ rdm_drupal_composer_dependencies|default([]) }}"
      become: no 

    - name: Install RDM configured modules with drush.
      command: "{{ drush_path }} --root={{ drupal_core_path }} -y en {{ rdm_drupal_enable_modules | join(' ') }}"
#      ignore_errors: yes

#    - name: Set ORCID client_id
#      command: "{{ drush_path }} --root {{ drupal_core_path }} cset orcid.settings client_id {{ orcid_client_id }} -y"
#      when: orcid_client_id is defined and orcid_client_id  != ''

#    - name: Set ORCID client_secret
#      command: "{{ drush_path }} --root {{ drupal_core_path }} cset orcid.settings client_secret {{ orcid_client_secret }} -y"
#      when: orcid_client_secret is defined and orcid_client_secret  != ''

    - name: Set ORCID name field
      command: "{{ drush_path }} --root {{ drupal_core_path }} cset orcid.settings name_field field_orcid_id  -y"

    - name: Set TUS Scheme
      command: "{{ drush_path }} --root {{ drupal_core_path }} cset tus.settings scheme public://  -y"

    - name: Check Deployment Addresses
      command: "sed -i 's/8000/{{ apache_listen_port }}/g' /opt/karaf/deploy/*"
      become_user: root

