- name: Adding extra packages for the RDM system
  hosts: webserver
  become: yes

  vars:
    rdm_drupal_composer_dependencies:
      - "drupal/conditional_fields:*" 
      - "drupal/markup:*"
      - "drupal/select_or_other:*"
      - "drupal/rules:*"
      - "drupal/clamav:*"
      - "islandora-rdm/islandora_rdm:*"

    rdm_drupal_enable_modules:
      - conditional_fields
      - markup
      - select_or_other
      - clamav
      - islandora_rdm 
      - data_management_plan

  tasks:
    - name: Ubuntu packages for RDM
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - clamav
        - clamav-daemon
      when: ansible_os_family == "Debian"

    - name: Install RDM dependencies with composer require (this may take a while).
      composer:
        command: require
        arguments: "{{ item }}"
        working_dir: "{{ drupal_composer_install_dir }}"
      with_items: "{{ rdm_drupal_composer_dependencies|default([]) }}"
      become: no

    - name: Install RDM configured modules with drush.
      command: "{{ drush_path }} --root={{ drupal_core_path }} -y en {{ rdm_drupal_enable_modules | join(' ') }}"


