- name: Adding extra packages for the RDM system
  hosts: webserver
  become: yes

  vars:
    rdm_drupal_composer_dependencies:
      - "dompdf/dompdf:*"
      - "drupal/conditional_fields:*" 
      - "drupal/markup:*"
      - "drupal/select_or_other:*"
      - "drupal/dynamic_entity_reference:2.0-alpha9"
      - "drupal/rules:*"
      - "drupal/clamav:*"
      - "drupal/entity_print:*"
      - "islandora-rdm/islandora_rdm:dev-8.x-1.x"
      - "drupal/orcid:1.x-dev"

    rdm_drupal_enable_modules:
      - conditional_fields
      - markup
      - select_or_other
      - clamav
      - entity_print
      - islandora_rdm 
      - islandora_rdm_site
      - islandora_rdm_data_management_plan
#      - islandora_rdm_solr_config
      - islandora_rdm_workflows
      - orcid

  tasks:
    - name: Ubuntu packages for RDM
      package:
        name: "{{ item }}"
        state: present
      with_items: 
        - php7.2-zip
      when: ansible_os_family == "Debian"

    - name: Install RDM dependencies with composer require (this may take a while).
      composer:
        command: require
        arguments: "{{ item }}"
        working_dir: "{{ drupal_composer_install_dir }}"
      with_items: "{{ rdm_drupal_composer_dependencies|default([]) }}"
      become: no 

    - name: Install RDM configured modules with drush.
      command: "{{ drush_path }} --root={{ drupal_core_path }} -y en {{ rdm_drupal_enable_modules | join(' ') }}"
#      ignore_errors: yes

#    - name: Set ORCID client_id
#      command: "{{ drush_path }} --root {{ drupal_core_path }} cset orcid.settings client_id {{ orcid_client_id }} -y"
#      when: orcid_client_id is defined and orcid_client_id  != ''

#    - name: Set ORCID client_secret
#      command: "{{ drush_path }} --root {{ drupal_core_path }} cset orcid.settings client_secret {{ orcid_client_secret }} -y"
#      when: orcid_client_secret is defined and orcid_client_secret  != ''

    - name: Set ORCID name field
      command: "{{ drush_path }} --root {{ drupal_core_path }} cset orcid.settings name_field  field_orcid_id  -y"

    - name: Setup clock syncing
      blockinfile:
        path: /etc/systemd/timesyncd.conf
        create: no
        insertafter: '^\[Time\]'
        content: |
          NTP=ur.ntp.srv
          FallbackNTP=ur.fallbackntp.srv


    - name: Sync clocks
      command: "{{ item }}"
      with_items:
        - sudo systemctl daemon-reload
        - sudo timedatectl set-ntp off
        - sudo timedatectl set-ntp on

