- src: geerlingguy.apache
  name: apache
  version: 2.1.1

- src: geerlingguy.php
  name: php
  version: 3.4.5

- src: geerlingguy.composer
  name: composer
  version: 1.6.1

- src: geerlingguy.git
  name: git
  version: 1.3.0

- src: geerlingguy.mysql
  name: mysql
  version: 2.7.2

- src: geerlingguy.postgresql
  name: postgresql
  version: 1.3.1

- src: geerlingguy.solr
  name: solr
  version: 3.5.5

- src: geerlingguy.java
  name: java
  version: 1.7.4

- src: geerlingguy.drupal
  name: drupal
  version: 2.2.2

- src: geerlingguy.drush
  name: drush
  version: 2.0.1

- src: geerlingguy.drupal-console
  name: drupal-console
  version: 1.1.0
