---

- hosts: webserver
  become: yes

  tasks:
    - name: "Install pdftotext (Debian family)"
      apt:
        name: poppler-utils
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install pdftotext (Redhat family)"
      yum:
        name: poppler-utils
        update_cache: yes
      when: ansible_os_family == "Redhat"

    - name: Download Islandora Text Extraction module
      composer:
        command: require
        arguments: islandora-rdm/islandora_text_extraction
        working_dir: "{{ drupal_core_path }}/.."

    - name: Enable text extraction module
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_text_extraction"
