---

- hosts: tomcat
  become: yes

  roles:
    - Islandora-Devops.tomcat8
    - Islandora-Devops.fcrepo
    - Islandora-Devops.fcrepo-syn
    - Islandora-Devops.blazegraph
    - name: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - Islandora-Devops.grok
    - Islandora-Devops.cantaloupe
    - Islandora-Devops.activemq
    - Islandora-Devops.fits
