---

hypercube:
  # path to the convert executable
  executable: tesseract

fedora_resource:
  base_url: http://localhost:8080/fcrepo/rest

log:
  # Valid log levels are:
  # DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY, NONE
  # log level none won't open logfile
  level: DEBUG
  file: /var/log/islandora/hypercube.log

syn:
  # toggles JWT security for service
  enable: true
  # Path to the syn config file for authentication.
  # example can be found here:
  # https://github.com/Islandora-CLAW/Syn/blob/master/conf/syn-settings.example.xml
  config: ../syn-settings.xml