---

- name: Configure Alpaca connector in Karaf
  lineinfile:
    dest: "{{ karaf_home }}/etc/ca.islandora.alpaca.connector.broadcast.cfg"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"
    regexp: '^input.stream='
    line: "input.stream= {{ alpaca_connector_queue }}"
- name: Configure Alpaca triplestore indexer in Karaf
  lineinfile:
    dest: "{{ karaf_home }}/etc/ca.islandora.alpaca.indexing.triplestore.cfg"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
     - { regexp: "^input.stream=", line: "input.stream={{ alpaca_indexer_queue }}" }
     - { regexp: "^triplestore.baseUrl=", line: "triplestore.baseUrl={{ triplestore_base_url }}" }
     - { regexp: "^drupal.username=", line: "drupal.username={{ drupal_user }}" }
     - { regexp: "^drupal.password=", line: "drupal.password={{ drupal_pass }}" }
  notify:
    - stop karaf
    - cleanup karaf
    - start karaf