---

- uri:
    url: "{{ apix_hypercube_service }}"
    headers:
      Bearer: "{{ apix_static_token }}"
    status_code: 200,404
  register: hypercube_service

- uri:
    url: "{{ apix_identify_service }}"
    headers:
      Bearer: "{{ apix_static_token }}"
    status_code: 200,404
  register: identify_service

- uri:
    url: "{{ apix_convert_service }}"
    headers:
      Bearer: "{{ apix_static_token }}"
    status_code: 200,404
  register: convert_service

- name: Load Hypercube
  uri:
    url: "{{ apix_loader_url }}"
    body: "{{ apix_hypercube_options_url }}"
    method: POST
    status_code: 200
    headers:
      Content-Type: text/plain
      Bearer: "{{ apix_static_token }}"
  when: hypercube_service.status == 404

- name: Load Identify
  uri:
    url: "{{ apix_loader_url }}"
    body: "{{ apix_identify_options_url }}"
    method: POST
    status_code: 200
    headers:
      Content-Type: text/plain
      Bearer: "{{ apix_static_token }}"
  when: identify_service.status == 404

- name: Load Convert
  uri:
    url: "{{ apix_loader_url }}"
    body: "{{ apix_convert_options_url }}"
    method: POST
    status_code: 200
    headers:
      Content-Type: text/plain
      Bearer: "{{ apix_static_token }}"
  when: convert_service.status == 404
