---

- name: Trusted Host Settings
  blockinfile:
    state: present
    block: |
      $settings['trusted_host_patterns'] = array(
      {% for host in drupal_trusted_hosts %}
        '{{ host }}',
      {% endfor %}
      );
    path: "{{ drupal_trusted_hosts_file }}"
    marker: // {mark} ANSIBLE MANAGED BLOCK

- name: Uninstall core search module
  command: drush -y pm-uninstall search
  args:
    chdir: "{{ drupal_core_path }}"
  register: uninstall_search
  changed_when: "'successfully uninstalled' in uninstall_search.stdout"

- name: Test if theme is Carapace
  command: drush -y config-get system.theme default
  args:
    chdir: "{{ drupal_core_path }}"
  register: drupal_theme_carapace
  changed_when: false
  check_mode: no

- name: Set theme to carapace
  command: drush -y config-set system.theme default carapace
  args:
    chdir: "{{ drupal_core_path }}"
  when: "'carapace' not in drupal_theme_carapace.stdout"

- name: Set permissions on the public files directory
  file:
    recurse: yes
    state: directory
    path: "{{ drupal_public_filesystem }}"
    owner: "{{ drupal_public_filesystem_user }}"
    group: "{{ drupal_public_filesystem_user }}"

- name: Create drupal configs directory.
  file:
    state: directory
    path: "{{ webserver_app_drupal_config_path }}"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"

- name: Copy members block config
  copy:
    src: block.block.views_block__membership_view_block_1.yml
    dest: "{{ webserver_app_drupal_config_path }}/block.block.views_block__membership_view_block_1.yml"
    mode: "0644"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
  register: drupal_member_block

- name: Install member block config
  command: drush config-import -y --partial --source="{{ webserver_app_drupal_config_path }}"
  args:
    chdir: "{{ drupal_core_path }}"
  when: drupal_member_block.changed is defined and drupal_member_block.changed
