---

- name: Trusted Host Settings
  blockinfile:
    state: present
    block: |
      $settings['trusted_host_patterns'] = array(
      {% for host in drupal_trusted_hosts %}
        '{{ host }}',
      {% endfor %}
      );
    path: "{{ drupal_trusted_hosts_file }}"
    marker: // {mark} ANSIBLE MANAGED BLOCK

- name: Uninstall core search module
  command: "{{ drush_path }} -y pm-uninstall search"
  args:
    chdir: "{{ drupal_core_path }}"
  register: uninstall_search
  changed_when: "'successfully uninstalled' in uninstall_search.stdout"

- name: Get Carapace status
  command: "{{ drush_path }} pm-list --format=json"
  args:
    chdir: "{{ drupal_core_path }}"
  register: carapace_enabled
  changed_when: false

- name: Enable Carapace if not enabled
  command: "{{ drush_path }} then -y carapace"
  args:
    chdir: "{{ drupal_core_path }}"
  when: ((carapace_enabled.stdout|from_json).carapace.status|lower) != 'enabled'

- name: Test if theme is Carapace
  command: "{{ drush_path }} -y config-get system.theme default"
  args:
    chdir: "{{ drupal_core_path }}"
  register: drupal_theme_carapace
  changed_when: false
  check_mode: no

- name: Set theme to carapace
  command: "{{ drush_path }} -y config-set system.theme default carapace"
  args:
    chdir: "{{ drupal_core_path }}"
  when: "'carapace' not in drupal_theme_carapace.stdout"

- name: Set permissions on the public files directory
  file:
    recurse: yes
    state: directory
    path: "{{ drupal_public_filesystem }}"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"

- name: Create drupal configs directory.
  file:
    state: directory
    path: "{{ webserver_app_drupal_config_path }}"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"

- name: Copy members block config
  copy:
    src: block.block.views_block__membership_view_block_1.yml
    dest: "{{ webserver_app_drupal_config_path }}/block.block.views_block__membership_view_block_1.yml"
    mode: "0644"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
  register: drupal_member_block

- name: Copy filehash config
  copy:
    src: filehash.settings.yml
    dest: "{{ webserver_app_drupal_config_path }}/filehash.settings.yml"
    mode: "0644"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
  register: drupal_filehash_settings

- name: Copy node REST config
  copy:
    src: rest.resource.entity.node.yml
    dest: "{{ webserver_app_drupal_config_path }}/rest.resource.entity.node.yml"
    mode: "0644"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
  register: drupal_node_rest

- name: Copy media REST config
  copy:
    src: rest.resource.entity.media.yml
    dest: "{{ webserver_app_drupal_config_path }}/rest.resource.entity.media.yml"
    mode: "0644"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
  register: drupal_media_rest

- name: Install config
  command: "{{ drush_path }} config-import -y --partial --source={{ webserver_app_drupal_config_path }}"
  args:
    chdir: "{{ drupal_core_path }}"
  when: (drupal_member_block.changed is defined and drupal_member_block.changed) or
        (drupal_filehash_settings.changed is defined and drupal_filehash_settings.changed) or
        (drupal_node_rest.changed is defined and drupal_node_rest.changed) or
        (drupal_media_rest.changed is defined and drupal_media_rest.changed)

- name: Set default solr server to point to CLAW core
  command: "{{ drush_path }} -y config-set search_api.server.default_solr_server backend_config.connector_config.core CLAW"
  args:
    chdir: "{{ drupal_core_path }}"
  register: set_search_api_config
  changed_when: "'Do you want to update' in set_search_api_config.stdout"

- name: Get solr config files to copy
  command: "find {{ webserver_document_root }}/drupal/web/modules/contrib/search_api_solr/solr-conf/6.x -type f"
  register: files_to_copy
  changed_when: false

- name: Copy solr config files
  copy:
    src: "{{ item }}"
    dest: "{{ solr_instance_conf_path }}"
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    remote_src: True
  with_items:
   - "{{ files_to_copy.stdout_lines }}"
  notify: restart solr
