---

- include: apache.yml
  when: webserver_app_apache
  tags:
    - webserver-app
    - webserver-app-apache

- include: drupal.yml
  when: webserver_app_drupal
  tags:
    - webserver-app
    - webserver-app-drupal

- include: jwt.yml
  when: webserver_app_jwt
  tags:
    - webserver-app
    - webserver-app-jwt

- include: fits.yml
  when: webserver_app_fits
  tags:
    - webserver-app
    - webserver-app-fits

- include: solr.yml
  when: webserver_app_drupal
  tags:
    - webserver-app
    - webserver-app-drupal

