---

- name: Download blazegraph war
  get_url:
    url: http://sourceforge.net/projects/bigdata/files/bigdata/{{ blazegraph_version }}/bigdata.war/download
    url: http://repo1.maven.org/maven2/com/blazegraph/bigdata-war/{{ blazegraph_version }}/bigdata-war-{{ blazegraph_version }}.war
    dest: "{{ blazegraph_war_path }}"
    owner: "{{ blazegraph_user }}"
    group: "{{ blazegraph_user }}"
  register: blazegraph_war_download
