---

- name: Install requisite packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - tesseract-ocr

- name: Install crayfish code
  git:
    repo: https://github.com/Islandora-CLAW/Crayfish.git
    dest: "/var/www/html/Crayfish"
    version: "{{ crayfish_version_tag }}"
    
- name: Build crayfish code including dependencies
  composer:
    command: install
    working_dir: /var/www/html/Crayfish/{{item}}
  with_items:
    - Gemini
    - Houdini
    - Milliner
    - Hypercube
    
- name: Configure crayfish code
  template:
    src: "{{item}}.config.example.yaml"
    dest: "/var/www/html/Crayfish/{{item}}/cfg/config.yaml"
  with_items:
    - Gemini
    - Houdini
    - Milliner
    - Hypercube
    
- name: Install auth config
  template:
    src: "syn-settings.xml"
    dest: "/var/www/html/Crayfish/{{item}}"
  with_items:
    - Gemini
    - Houdini
    - Milliner
    - Hypercube

- name: Create Gemini db
  mysql_db:
    name: gemini
    state: present

- name: Grab Gemini db schema
  template:
    src: "gemini.sql"
    dest: "/tmp/gemini.sql"

- name: Install Gemini db schema
  mysql_db:
    state: import
    name: all
    target: "/tmp/gemini.sql"
    
- name: Create Islandora log dir
  file:
    path: /var/log/islandora
    state: directory
    owner: www-data
    group: www-data
    mode: "u+rwx,g+r,o-rwx"
    
- name: Create Gemini log
  file:
    path: /var/log/islandora/gemini.log
    state: touch
    owner: www-data
    group: www-data
    mode: "u+rw,g+r,o-rwx"

- name: Install crayfish httpd config file
  template:
    src: "crayfish.conf"
    dest: "/etc/apache2/conf-available/crayfish.conf"
    owner: "{{ crayfish_user }}"
    group: "{{ crayfish_user }}"

- name: Symlink crayfish httpd config file into action
  file:
    src: "/etc/apache2/conf-available/crayfish.conf"
    dest: "/etc/apache2/conf-enabled/crayfish.conf"
    owner: "{{ crayfish_user }}"
    group: "{{ crayfish_user }}"
    state: link
  notify: restart crayfish
