---

apix_feature_repo: mvn:org.fcrepo.apix/fcrepo-api-x-karaf/LATEST/xml/features
apix_feature:
  - fcrepo-api-x
  - fcrepo-indexing-triplestore
  - fcrepo-service-camel

apix_hypercube_service: http://localhost:8081/fcrepo/rest/apix/services/CLAW-OcrService
apix_identify_service: http://localhost:8081/fcrepo/rest/apix/services/CLAW-IdentifyService
apix_convert_service: http://localhost:8081/fcrepo/rest/apix/services/CLAW-ConvertService

apix_hypercube_options_url: http://localhost:8000/hypercube/
apix_identify_options_url: http://localhost:8000/houdini/identify
apix_convert_options_url: http://localhost:8000/houdini/convert

apix_static_token: islandora

apix_loader_url: http://localhost:8081/services//apix:load

apix_root_discovery: http://localhost:8081/discovery/

apix_karaf_etc_dir: "{{ karaf_install_symlink }}/etc"

apix_config:
  - pid: org.fcrepo.apix.registry.http
    settings:
      timeout.socket.ms: 1000
  - pid: org.fcrepo.camel.indexing.triplestore
    settings:
      input.stream: activemq:topic:fedora
      triplestore.reindex.stream: activemq:queue:triplestore.reindex
      triplestore.baseUrl: http://localhost:8080/bigdata/namespace/islandora/sparql
